{{- if not .Values.rollout.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-service.labels" . | nindent 6 }}
  template:
    {{- include "base-service.podTemplateSpec" . | nindent 4 }}
{{- end }}
