# WO-026: the platform's single edge entry point — NGINX Ingress
# Controller terminates TLS 1.3 for every inbound request, and
# cert-manager issues/rotates both the public-facing TLS certificate and
# the internal CA used for mTLS between the gateway and backend services.
# Both "ingress-nginx" and "cert-manager" namespaces already exist as
# system namespaces (namespaces.tf) — these releases install INTO them
# rather than creating their own.

resource "helm_release" "ingress_nginx" {
  name             = "ingress-nginx"
  repository       = "https://kubernetes.github.io/ingress-nginx"
  chart            = "ingress-nginx"
  version          = "4.11.3"
  namespace        = "ingress-nginx"
  create_namespace = false

  set {
    name  = "controller.replicaCount"
    value = "3" # HA — every request in the platform passes through this
  }

  # TLS 1.3 only — the acceptance criteria requires TLS 1.0/1.1 REJECTED,
  # not merely TLS 1.3 offered alongside them. Listing only TLSv1.3 here
  # is what actually enforces that, not a lower bound.
  set {
    name  = "controller.config.ssl-protocols"
    value = "TLSv1.3"
  }
  set {
    name  = "controller.config.ssl-ciphers"
    value = "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
  }
  # X-Request-ID: generated by NGINX itself for every request that doesn't
  # already carry one (client-supplied ids are honored, not overwritten) —
  # satisfies the correlation-id acceptance criteria without needing a
  # custom Lua/OpenResty script.
  set {
    name  = "controller.config.generate-request-id"
    value = "true"
  }
  set {
    name  = "controller.config.use-forwarded-headers"
    value = "true"
  }
  # Structured JSON access logs: timestamp, request id, upstream, latency,
  # status, client ip — tenant_id/user_id are NOT logged at the gateway
  # (see README's "Where JWT validation happens" section for why), so
  # they're absent from this format; each backend service's own audit
  # trail (already built — postgres-audit.service.ts) is authoritative
  # for actor/tenant-attributed logging.
  set {
    name  = "controller.config.log-format-escape-json"
    value = "true"
  }
  set {
    name  = "controller.config.log-format-upstream"
    value = "{\"timestamp\":\"$time_iso8601\",\"request_id\":\"$req_id\",\"method\":\"$request_method\",\"path\":\"$uri\",\"status\":$status,\"latency_ms\":$request_time,\"upstream_service\":\"$proxy_upstream_name\",\"client_ip\":\"$remote_addr\"}"
  }

  # Load-shedding / WAF-adjacent cross-cutting concern this WO calls out —
  # a real WAF (AWS WAF via the NLB in front of this, or ModSecurity) is a
  # separate work order; NGINX's own connection-level rate limit is the
  # floor every request is subject to regardless.
  set {
    name  = "controller.config.limit-req-status-code"
    value = "429"
  }

  depends_on = [kubernetes_namespace.system, aws_eks_node_group.system]
}

resource "helm_release" "cert_manager" {
  name             = "cert-manager"
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = "1.16.2"
  namespace        = "cert-manager"
  create_namespace = false

  set {
    name  = "installCRDs"
    value = "true"
  }
  set {
    name  = "replicaCount"
    value = "2" # HA — every cert issuance/renewal (public TLS + mTLS) depends on this controller
  }

  depends_on = [kubernetes_namespace.system, aws_eks_node_group.system]
}

# --- Public-facing TLS: ACME (Let's Encrypt) via HTTP-01 --------------------

resource "kubernetes_manifest" "public_tls_issuer" {
  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "public-tls-issuer"
    }
    spec = {
      acme = {
        server = "https://acme-v02.api.letsencrypt.org/directory"
        email  = var.tls_admin_email
        privateKeySecretRef = {
          name = "public-tls-issuer-account-key"
        }
        solvers = [{
          http01 = {
            ingress = {
              class = "nginx"
            }
          }
        }]
      }
    }
  }

  depends_on = [helm_release.cert_manager]
}

# --- Internal CA for mTLS between the gateway and backend services --------
# Two-tier bootstrap (cert-manager's standard pattern): a self-signed
# issuer mints the CA certificate itself, then a second ClusterIssuer
# referencing that CA's secret is what actually issues every backend
# service's mTLS certificate. 90-day validity + a 30-day renewBefore
# window on every leaf certificate is the "90-day automatic rotation"
# this WO's acceptance criteria call for.

resource "kubernetes_manifest" "internal_ca_bootstrap_issuer" {
  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "internal-ca-bootstrap"
    }
    spec = {
      selfSigned = {}
    }
  }

  depends_on = [helm_release.cert_manager]
}

resource "kubernetes_manifest" "internal_ca_certificate" {
  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Certificate"
    metadata = {
      name      = "ams-internal-ca"
      namespace = "cert-manager"
    }
    spec = {
      isCA        = true
      commonName  = "ams-internal-ca"
      secretName  = "ams-internal-ca-secret"
      duration    = "8760h" # 1 year — the CA itself, not the leaf certs
      renewBefore = "720h"  # 30 days
      privateKey = {
        algorithm = "ECDSA"
        size      = 256
      }
      issuerRef = {
        name  = "internal-ca-bootstrap"
        kind  = "ClusterIssuer"
        group = "cert-manager.io"
      }
    }
  }

  depends_on = [kubernetes_manifest.internal_ca_bootstrap_issuer]
}

resource "kubernetes_manifest" "internal_mtls_issuer" {
  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "ams-internal-mtls-issuer"
    }
    spec = {
      ca = {
        secretName = "ams-internal-ca-secret"
      }
    }
  }

  depends_on = [kubernetes_manifest.internal_ca_certificate]
}

# One mTLS leaf certificate per bounded-context service — 90-day validity,
# auto-renewed 30 days before expiry, matching this WO's rotation requirement.
resource "kubernetes_manifest" "backend_mtls_certificate" {
  for_each = kubernetes_namespace.bounded_context

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Certificate"
    metadata = {
      name      = "${each.key}-mtls-cert"
      namespace = each.value.metadata[0].name
    }
    spec = {
      secretName  = "${each.key}-mtls-tls"
      duration    = "2160h" # 90 days
      renewBefore = "720h"  # 30 days
      dnsNames    = ["${each.key}.${each.value.metadata[0].name}.svc.cluster.local"]
      issuerRef = {
        name  = "ams-internal-mtls-issuer"
        kind  = "ClusterIssuer"
        group = "cert-manager.io"
      }
    }
  }

  depends_on = [kubernetes_manifest.internal_mtls_issuer]
}
