"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { Button } from "@/components/ui/button";
import { HealthHistoryChart } from "@/components/dashboard/health-history-chart";
import { LifecycleHistoryList } from "@/components/dashboard/lifecycle-history-list";
import { QualityDriftBadge } from "@/components/dashboard/quality-drift-badge";
import { TimeRangeSelector } from "@/components/dashboard/time-range-selector";
import { TraceTimeline } from "@/components/dashboard/trace-timeline";
import { useAgentHealthHistoryQuery, useAgentLifecycleHistoryQuery, useAgentTracesQuery } from "@/hooks/useAgentHealthDetailQueries";
import type { TimeRange } from "@/types/dashboard";

/**
 * AC: drill-down from the overview dashboard. A ?agentId= query param
 * route, not a [agentId] dynamic segment: this frontend builds as a
 * static export (next.config.js `output: "export"`, per WO-050), which
 * requires every dynamic route to have its params known at BUILD time
 * (generateStaticParams) — agent IDs plainly aren't. The WO's own spec
 * text names a `[agentId]` path; this is the same class of "existing
 * codebase constraint overrides an autogenerated WO's exact wording" call
 * already made for this route's own parent path in page.tsx.
 */
export default function AgentHealthDetailPage() {
  return (
    <Suspense fallback={<p role="status">Loading…</p>}>
      <AgentHealthDetailPageContent />
    </Suspense>
  );
}

function AgentHealthDetailPageContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const agentId = searchParams.get("agentId") ?? "";
  const [range, setRange] = useState<TimeRange>("24h");

  const historyQuery = useAgentHealthHistoryQuery(agentId, range);
  const tracesQuery = useAgentTracesQuery(agentId);
  const lifecycleQuery = useAgentLifecycleHistoryQuery(agentId);

  if (!agentId) {
    return <p role="alert">No agent selected.</p>;
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" onClick={() => router.push("/agents/health")}>
          ← Back to fleet overview
        </Button>
        <h2 className="text-xl font-semibold">Agent Health Detail</h2>
      </div>

      {historyQuery.isLoading && <p role="status">Loading health history…</p>}
      {historyQuery.isError && <p role="alert">Unable to load health history for this agent right now.</p>}

      {historyQuery.data && (
        <>
          <QualityDriftBadge qualityScore={historyQuery.data.qualityScore} driftStatus={historyQuery.data.driftStatus} />

          <div className="flex items-center justify-between gap-4">
            <h3 className="text-lg font-medium">Historical Metrics</h3>
            <TimeRangeSelector value={range} onChange={setRange} />
          </div>
          <HealthHistoryChart points={historyQuery.data.points} />
        </>
      )}

      <div>
        <h3 className="mb-2 text-lg font-medium">Recent Execution Traces</h3>
        {tracesQuery.isLoading && <p role="status">Loading traces…</p>}
        {tracesQuery.data && <TraceTimeline traces={tracesQuery.data.rows} />}
      </div>

      <div>
        <h3 className="mb-2 text-lg font-medium">Lifecycle History</h3>
        {lifecycleQuery.isLoading && <p role="status">Loading lifecycle history…</p>}
        {lifecycleQuery.data && <LifecycleHistoryList entries={lifecycleQuery.data} />}
      </div>

      <div>
        <h3 className="mb-2 text-lg font-medium">Alerts</h3>
        {/* Honest scope note: no alerts data model exists yet in this
            codebase (AlertsGateway is a WebSocket channel shell with no
            persisted alert records behind it) — configurable thresholds
            (WO-059) and multi-channel delivery (WO-060) are what will
            eventually populate this section. Not fabricating alert data
            here. */}
        <p className="text-muted-foreground text-sm" role="status">
          Alerting is not yet available for this agent.
        </p>
      </div>
    </div>
  );
}
